### PR TITLE
Change context.workspace to context.projectsConfigurations

### PR DESCRIPTION
**Pull request by Ionaru**
## Current Behavior

@nxkit/style-dictionary no longer runs with NX v20, throwing this error:

```
TypeError: Cannot read properties of undefined (reading 'projects')
    at normalizeOptions (/opt/atlassian/pipelines/agent/build/node_modules/@nxkit/style-dictionary/src/executors/build/lib/normalize-options.js:7:45)
    at /opt/atlassian/pipelines/agent/build/node_modules/@nxkit/style-dictionary/src/executors/build/executor.js:13:76
    at Generator.next (<anonymous>)
    at /opt/atlassian/pipelines/agent/build/node_modules/tslib/tslib.js:170:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/atlassian/pipelines/agent/build/node_modules/tslib/tslib.js:166:16)
    at buildExecutor (/opt/atlassian/pipelines/agent/build/node_modules/@nxkit/style-dictionary/src/executors/build/executor.js:12:20)
    at runExecutorInternal (/opt/atlassian/pipelines/agent/build/node_modules/nx/src/command-line/run/run.js:98:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/atlassian/pipelines/agent/build/node_modules/nx/src/command-line/run/run.js:176:44
```

## Expected Behavior

No error is thrown and the plugin works.

## Related Issue(s)

Caused by https://github.com/nrwl/nx/issues/28461, `workspace` no longer exists in `ExecutorContext`.
The alternative, `projectsConfigurations` has been available since NX v16, so we can use that.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by Ionaru** [comment]
@sebastiandg7 I am not sure why the CI failed, any ideas?

**Comment by sebastiandg7** [comment]
Hey @Ionaru, thanks for reporting. I'll take a look today.

**Comment by atomicrobokid** [comment]
@sebastiandg7 - any chance of getting this merged/versioned a.s.a.p? It's preventing our migration to nx `20.0.8` - it's the only plugin causing us issues. Thanks :)

**Comment by sebastiandg7** [comment]
Let's move with this in #110

**Comment by sebastiandg7** [comment]
@allcontributors add @Ionaru for bugs

**Pull request closed without merging**
