### PR TITLE
fix(playwright): project output path

### LINKED ISSUE #63: Playwright project.json outputPath and actual path of output don't match
### Current Behavior

Generating a new project doesn't set the proper outputPath in the project.json (which leads to the e2e output not being recovered from cache in CI). When generating an e2e app for 'my-app' and running the e2e target, the actual outputPath is `dist/apps/my-app-e2e/playwright-report` while the config in the project.json points to `dist/apps/my-app-e2e/test-results`.

### Expected Behaviour

The output path of the reporters in the `playwright.config.ts` should match the outputpath in the e2e and debug targets in the `project.json`.

### Github Repo

https://github.com/JoepKockelkorn/nxkit-playwright-outputpath-bug

### Steps to Reproduce

1. run `npx nx generate @nxkit/playwright:project my-app-e2e --frontendProject=my-app --no-interactive`
2. run `npx nx e2e my-app-e2e`
3. see `dist/apps/my-app-e2e/playwright-report` folder is populated
4. delete that folder
5. rerun `npx nx e2e my-app-e2e`
6. see that the output is not recovered from cache because of the wrong outputpath in `project.json`

### Nx Report

```shell
Node : 16.16.0
OS   : darwin x64
npm  : 8.11.0

nx                      : 15.8.6
@nrwl/js                : 15.8.6
@nrwl/linter            : 15.8.6
@nrwl/workspace         : 15.8.6
@nrwl/cli               : 15.8.6
@nrwl/cypress           : 15.8.6
@nrwl/devkit            : 15.8.6
@nrwl/eslint-plugin-nx  : 15.8.6
@nrwl/react             : 15.8.6
@nrwl/tao               : 15.8.6
@nrwl/vite              : 15.8.6
typescript              : 4.9.5
---------------------------------------
Community plugins:
@nxkit/playwright : 2.1.2
```

### Failure Logs

_No response_

### Additional Information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JoepKockelkorn**
ISSUES CLOSED: #63

## Current Behavior

See https://github.com/nxkit/nxkit/issues/63.

## Expected Behavior

The output path of the reporters in the playwright.config.ts should match the outputpath in the e2e and debug targets in the project.json.

## Related Issue(s)

Fixes #63

# Checklist:

- [x] My code follows the [developer guidelines of this project]
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by JoepKockelkorn** [comment]
Hmmm, after my change the following message shows in the console:
```
Configuration Error: HTML reporter output folder clashes with the tests output folder
```
Trying to figure out how to combine all configuration into a place where we still have NX cache recovery

UPDATE: fixed it in [c457c8b](https://github.com/nxkit/nxkit/pull/64/commits/c457c8b6f89f8448db1c4e05fa805b27782f0f76) by reverting the outputPath by changing the nx outputs config to point to the `dist/my-app-e2e/` folder.

**Review by sebastiandg7 — APPROVED** [review]

**Comment by sebastiandg7** [comment]
@all-contributors please add @JoepKockelkorn  for code and issues

**Comment by sebastiandg7** [comment]
@allcontributors please add @JoepKockelkorn for bug

**Comment by sebastiandg7** [comment]
@allcontributors please add @JoepKockelkorn for bug

**Pull request merged**
