### PR TITLE
chore: upgrade nx to 15.8

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Current Behavior
Nx has moved `getRelativePathToRootTsConfig` to another package in version 15.8. Because of this when upgrading projects to latest version, nxkit packages will stop working

## Expected Behavior
Should also bump the version of nx

## Related Issue(s)

Fixes #

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by dmitry-stepanenko** [comment]
@sebastiandg7 I'm not sure why format check is failing, all files are formatted properly. Looks like the same is happening on your other PR here. Any ideas?

**Comment by sebastiandg7** [comment]
Let me give it a look. I'll add a NX compatibility table to the Readme so it's clear what versions can be used with Nx.

**Comment by sebastiandg7** [comment]
@dmitry-stepanenko I'm facing the same formatting issue with the `pnpm-lock.yaml` not only with this repo. Not sure why 🤔 , would you like to add that file to the `.prettierignore`?

**Comment by dmitry-stepanenko** [comment]
@sebastiandg7 thanks, done

**Comment by sebastiandg7** [comment]
@dmitry-stepanenko E2E tests are failing... seems like the Jest v29 migration didn't update the jest config files? Did you run the migrations?

**Comment by dmitry-stepanenko** [comment]
Yeah, I saw. And I did run the migrations. Will look into this in a while

**Comment by dmitry-stepanenko** [comment]
@sebastiandg7 it looks like `npx create-nx-workspace --preset=empty` does not generate tsconfig.base.json anymore. I've added handling for this.

**Comment by dmitry-stepanenko** [comment]
@sebastiandg7 sorry for pushing, but we urgently need a new version both for nxkit and qwik plugins, because everything is broken for folks who try to use them. Can you please merge this PR or give me the feedback on it?

**Review by sebastiandg7 — APPROVED** [review]

**Comment by sebastiandg7** [comment]
@dmitry-stepanenko sorry for the delay! Just published v2.1.2 with the fix 👌🏻

**Comment by dmitry-stepanenko** [comment]
Thanks a lot!

**Pull request merged**
