### PR TITLE
feat(core): Add compatibility with nx 20

### PR DESCRIPTION
**Pull request by Ionaru**
- Ran `nx migrate latest` and `nx migrate --run-migrations` to update nx to version 20
- Fixed test in `packages/playwright/src/executors/test/executor.spec.ts`: `ExecutorContext` type changed.
- Removed all `qwik` packages
- Updated versions of other packages to resolve peer dependency warnings
- Ran `pnpm update` a few times
- Added missing `5.0.0` to "NxKit & Nx Compatibility" table
- Added (presumed) `6.0.0` to "NxKit & Nx Compatibility" table

### CODE REVIEW

**Review by sebastiandg7 — APPROVED** [review]

**Comment by sebastiandg7** [comment]
Hey @Ionaru! This looks good. Thank you for the contribution here. 

`qwik-nx` was there to build a small docs site using qwik, which can be resumed later. 

Is this good to merge? I can skip ci checks as I need to update the workflow as well

**Comment by Ionaru** [comment]
@sebastiandg7 Not quite yet. I am still running some checks & tests to make sure it all works :)

**Comment by Ionaru** [comment]
@sebastiandg7 [`d0fafd3` (#110)](https://github.com/nxkit/nxkit/pull/110/commits/d0fafd34eaaafbaecd33c24dc4cf5b831ba47e7b) fixes a build issue with the playwright package. Everything seems to work now except the e2e tests for playwright, it times out.

**Comment by sebastiandg7** [comment]
Not a problem, since the official Nx plugin for playwright replaces this one. I'll do some clean up and deprecate it. Thank you! 

I'll have this released today.

**Comment by atomicrobokid** [comment]
> Not a problem, since the official Nx plugin for playwright replaces this one. I'll do some clean up and deprecate it. Thank you!
> 
> I'll have this released today.

Not to be a nag @sebastiandg7, but did you get any closer to getting this merged/released?

**Comment by sebastiandg7** [comment]
Sorry for the time taken. Just released [6.0.0](https://github.com/nxkit/nxkit/releases/tag/6.0.0) with these changes 👍🏻

**Comment by atomicrobokid** [comment]
Legend, thank you!

**Pull request merged**
